#lang racket
(require redex)

;; grammar for html
;; using spec from http://www.cs.utah.edu/plt/snapshots/current/doc/html/index.html

;; non-terminals have "$" prefix, eh $attr
(define-language HTML
  ($html (html $attrs $html-contents))
  ($html-contents ($html-content ...))
  ($html-content $head $body)

  ($attr (attr $name $val))
  ($attrs ($attr ...))
  ($name string)
  ($val string natural)

  ($head (head $attrs $head-contents))
  ($head-contents ($head-content ...))
  ($head-content $base $isindex $alink $meta $object $script $style $title)
  ($base (base $attrs))
  ($isindex (isindex $attrs))
  ($alink (alink $attrs))
  ($meta (meta $attrs))
  ($object (object $attrs $obj-contents))
  ($obj-contents ($obj-content ...))
  ($obj-content $param $g2)
  ($param (param $attrs))
  ($script (script $attrs $pcdatas))
  ($pcdatas ($pcdata ...))
  ($pcdata (pcdata string))
  ($style (style $attrs $pcdatas))
  ($title (title $attrs $pcdatas))
  
  ($body (body $attrs $body-contents))
  ($body-contents ($body-content ...))
  ($body-content $del $ins $g2)
  ($del (del $attrs $g2s))
  ($ins (ins $attrs $g2s))
  ;; g2
  ($g2s ($g2 ...))
  ($g2 $form $g3)
  ($form (form $attrs $g3s))
  ;; g3
  ($g3s ($g3 ...))
  ($g3 $fieldset $isindex $g4 $g11)
  ($fieldset (fieldset $attrs $fieldset-contents))
  ($fieldset-contents ($fieldset-content ...))
  ($fieldset-content $legend $g2)
  ($legend (legend $attrs $g5s))
  ;; g4
  ($g4 $g8 $g10)
  ;; g5
  ($g5s ($g5 ...))
  ($g5 $label $g6)
  ($label (label $attrs $g6s))
  ;; g6
  ($g6s ($g6 ...))
  ($g6 $a $g7)
  ($a (a $attrs $a-contents))
  ($a-contents ($a-content ...))
  ($a-content $label $g7)
  ;; g7
  ($g7 $g8 $g12)
  ;; g8
  ($g8 $applet $basefont $big $font $img $object $small $sub $sup $g9)
  ($applet (applet $attrs $applet-contents))
  ($applet-contents ($applet-content ...))
  ($applet-content $param $g2)
  ($basefont (basefont $attrs))
  ($big (big $attrs $g5s))
  ($font (font $attrs $g5s))
  ($img (img $attrs))
  ($small (small $attrs $g5s))
  ($sub (sub $attrs $g5s))
  ($sup (sup $attrs $g5s))
  ;; g9
  ($g9 $abbr $acronym $b $bdo $br $cite $code $dfn $em $i $kbd $map $pcdata $q
       $s $samp $script $span $strike $strong $tt $u $var)
  ($abbr (abbr $attrs $g5s))
  ($acronym (acronyms $attrs $g5s))
  ($b (b $attrs $g5s))
  ($bdo (bdo $attrs $g5s))
  ($br (br $attrs))
  ($cite (cite $attrs $g5s))
  ($code (code $attrs $g5s))
  ($dfn (dfn $attrs $g5s))
  ($em (em $attrs $g5s))
  ($i (i $attrs $g5s))
  ($kbd (kbd $attrs $g5s))
  ($map (map $attrs $map-contents))
  ($map-contents ($map-content ...))
  ($map-content $area $fieldset $form $isindex $g10)
  ($area (area $attrs))
  ($q (q $attrs $g5s))
  ($s (s $attrs $g5s))
  ($samp (samp $attrs $g5s))
  ($span (span $attrs $g5s))
  ($strike (strike $attrs $g5s))
  ($strong (strong $attrs $g5s))
  ($tt (tt $attrs $g5s))
  ($u (u $attrs $g5s))
  ($var (var $attrs $g5s))
  ;; g10
  ($g10 $address $blockquote $center $dir $div $dl $h1 $h2 $h3 $h4 $h5 $h6 $hr
        $menu $noframes $noscript $ol $p $pre $table $ul)
  ($address (address $attrs $addr-contents))
  ($addr-contents ($addr-content ...))
  ($addr-content $p $g5)
  ($blockquote (blockquote $attrs $g2s))
  ($center (center $attrs $g2s))
  ($dir (dir $attrs $lis))
  ($div (div $attrs $g2s))
  ($dl (dl $attrs $dl-contents))
  ($dl-contents ($dl-content ...))
  ($dl-content $dd $dt)
  ($dd (dd $attrs $g2s))
  ($dt (dt $attrs $g5s))
  ($lis ($li ...))
  ($li (li $attrs $g2s))
  ($h1 (h1 $attrs $g5s))
  ($h2 (h2 $attrs $g5s))
  ($h3 (h3 $attrs $g5s))
  ($h4 (h4 $attrs $g5s))
  ($h5 (h5 $attrs $g5s))
  ($h6 (h6 $attrs $g5s))
  ($hr (hr $attrs))
  ($menu (menu $attsr $lis))
  ($noframes (noframes $attrs $g2s))
  ($noscript (noscript $attrs $g2s))
  ($ol (ol $attrs $lis))
  ($p (p $attrs $g5s))
  ($pre (pre $attrs $pre-contents))
  ($pre-contents ($pre-content ...))
  ($pre-content $g9 $g11)
  ;;table
  ($table (table $attrs $table-contents))
  ($table-contents ($table-content ...))
  ($table-content $caption $col $colgroup $tbody $tfoot $thead)
  ($caption (caption $attrs $g5s))
  ($cols ($col ...))
  ($col (col $attrs))
  ($colgroup (colgroup $cols))
  ($thead (thead $attrs $trs))
  ($tfoot (tfoot $attrs $trs))
  ($tbody (tbody $attrs $trs))
  ($trs ($tr ...))
  ($tr (tr $attrs $tr-contents))
  ($tr-contents ($tr-content ...))
  ($tr-content $td $th)
  ($td (td $attrs $g2s))
  ($th (th $attrs $g2s))
  ;; end table
  ($ul (ul $attrs $lis))
  ;; g11
  ($g11 $a $label $g12)
  ;; g12
  ($g12 $del $ins $g2)

  )
  
  

(define (checker h) (printf "~v\n" h) #t)

(redex-check HTML $html (checker (term $html)))