name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *' # 00:00 1st day of month

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        racket_version:
          - '6.9'
          - 'stable'
          - 'current'
    name: Test Racket ${{ matrix.racket_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: 'x64'
          distribution: 'full'
          version: ${{ matrix.racket_version }}
      - name: Install Package
        run: make install
      - name: Check Deps
        run: make check-deps
      - name: Run Tests
        run: make test
